services:
  postgres:
    image: postgres:18
    container_name: summit-postgres
    environment:
      POSTGRES_USER: summit
      POSTGRES_PASSWORD: summit
      POSTGRES_DB: summit
    ports:
      - "5433:5432"
    volumes:
      - summit_postgres_data_v18:/var/lib/postgresql

volumes:
  summit_postgres_data_v18:
