CREATE TABLE "series_analysis_reader_capabilities" (
	"reader_id" text PRIMARY KEY NOT NULL,
	"artifact_schema_versions" jsonb NOT NULL,
	"draining" boolean DEFAULT false NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"heartbeat_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "series_analysis_reader_capabilities_schemas_array_check" CHECK (jsonb_typeof("series_analysis_reader_capabilities"."artifact_schema_versions") = 'array')
);
--> statement-breakpoint
ALTER TABLE "series_analysis_artifacts" DROP CONSTRAINT "series_analysis_artifacts_bytes_check";--> statement-breakpoint
ALTER TABLE "series_analysis_drilldown_artifacts" DROP CONSTRAINT "series_analysis_drilldown_artifacts_chunk_check";--> statement-breakpoint
ALTER TABLE "series_analysis_match_context_artifacts" DROP CONSTRAINT "series_analysis_match_context_artifacts_chunk_check";--> statement-breakpoint
ALTER TABLE "series_analysis_scope_aggregate_artifacts" DROP CONSTRAINT "series_analysis_scope_aggregate_artifacts_chunk_check";--> statement-breakpoint
ALTER TABLE "series_analysis_scope_review_artifacts" DROP CONSTRAINT "series_analysis_scope_review_artifacts_chunk_check";--> statement-breakpoint
CREATE INDEX "series_analysis_reader_capabilities_heartbeat_idx" ON "series_analysis_reader_capabilities" USING btree ("heartbeat_at");--> statement-breakpoint
ALTER TABLE "series_analysis_artifacts" ADD CONSTRAINT "series_analysis_artifacts_bytes_check" CHECK ("series_analysis_artifacts"."encoded_bytes" >= 0 AND "series_analysis_artifacts"."decoded_bytes" = "series_analysis_artifacts"."encoded_bytes");--> statement-breakpoint
ALTER TABLE "series_analysis_drilldown_artifacts" ADD CONSTRAINT "series_analysis_drilldown_artifacts_chunk_check" CHECK ("series_analysis_drilldown_artifacts"."encoded_bytes" >= 2 AND "series_analysis_drilldown_artifacts"."encoded_bytes" = octet_length("series_analysis_drilldown_artifacts"."payload") AND "series_analysis_drilldown_artifacts"."decoded_bytes" = "series_analysis_drilldown_artifacts"."encoded_bytes" AND "series_analysis_drilldown_artifacts"."item_count" >= 0 AND "series_analysis_drilldown_artifacts"."nesting_depth" BETWEEN 1 AND 64 AND "series_analysis_drilldown_artifacts"."checksum" ~ '^sha256:[0-9a-f]{64}$');--> statement-breakpoint
ALTER TABLE "series_analysis_match_context_artifacts" ADD CONSTRAINT "series_analysis_match_context_artifacts_chunk_check" CHECK ("series_analysis_match_context_artifacts"."encoded_bytes" >= 2 AND "series_analysis_match_context_artifacts"."encoded_bytes" = octet_length("series_analysis_match_context_artifacts"."payload") AND "series_analysis_match_context_artifacts"."decoded_bytes" = "series_analysis_match_context_artifacts"."encoded_bytes" AND "series_analysis_match_context_artifacts"."item_count" >= 0 AND "series_analysis_match_context_artifacts"."nesting_depth" BETWEEN 1 AND 64 AND "series_analysis_match_context_artifacts"."checksum" ~ '^sha256:[0-9a-f]{64}$');--> statement-breakpoint
ALTER TABLE "series_analysis_scope_aggregate_artifacts" ADD CONSTRAINT "series_analysis_scope_aggregate_artifacts_chunk_check" CHECK ("series_analysis_scope_aggregate_artifacts"."encoded_bytes" >= 2 AND "series_analysis_scope_aggregate_artifacts"."encoded_bytes" = octet_length("series_analysis_scope_aggregate_artifacts"."payload") AND "series_analysis_scope_aggregate_artifacts"."decoded_bytes" = "series_analysis_scope_aggregate_artifacts"."encoded_bytes" AND "series_analysis_scope_aggregate_artifacts"."item_count" >= 0 AND "series_analysis_scope_aggregate_artifacts"."nesting_depth" BETWEEN 1 AND 64 AND "series_analysis_scope_aggregate_artifacts"."checksum" ~ '^sha256:[0-9a-f]{64}$');--> statement-breakpoint
ALTER TABLE "series_analysis_scope_review_artifacts" ADD CONSTRAINT "series_analysis_scope_review_artifacts_chunk_check" CHECK ("series_analysis_scope_review_artifacts"."encoded_bytes" >= 2 AND "series_analysis_scope_review_artifacts"."encoded_bytes" = octet_length("series_analysis_scope_review_artifacts"."payload") AND "series_analysis_scope_review_artifacts"."decoded_bytes" = "series_analysis_scope_review_artifacts"."encoded_bytes" AND "series_analysis_scope_review_artifacts"."item_count" >= 0 AND "series_analysis_scope_review_artifacts"."nesting_depth" BETWEEN 1 AND 64 AND "series_analysis_scope_review_artifacts"."checksum" ~ '^sha256:[0-9a-f]{64}$');