ALTER TABLE "series_analysis_artifacts" DROP CONSTRAINT "series_analysis_artifacts_validation_schema_check";--> statement-breakpoint
ALTER TABLE "series_analysis_campaign_targets" DROP CONSTRAINT "series_analysis_campaign_targets_validation_schema_check";--> statement-breakpoint
ALTER TABLE "series_analysis_campaigns" DROP CONSTRAINT "series_analysis_campaigns_validation_schema_check";--> statement-breakpoint
ALTER TABLE "series_analysis_job_attempts" DROP CONSTRAINT "series_analysis_job_attempts_validation_schema_check";--> statement-breakpoint
ALTER TABLE "series_analysis_job_requests" DROP CONSTRAINT "series_analysis_job_requests_validation_schema_check";--> statement-breakpoint
ALTER TABLE "series_analysis_jobs" DROP CONSTRAINT "series_analysis_jobs_validation_schema_check";--> statement-breakpoint
ALTER TABLE "series_analysis_release_state" DROP CONSTRAINT "series_analysis_release_state_validation_schema_check";--> statement-breakpoint
ALTER TABLE "series_analysis_title_states" DROP CONSTRAINT "series_analysis_title_states_validation_schema_check";--> statement-breakpoint
ALTER TABLE "series_analysis_release_state" ALTER COLUMN "algorithm_version" SET DEFAULT 'series-analysis-v5';--> statement-breakpoint
ALTER TABLE "series_analysis_release_state" ALTER COLUMN "artifact_schema_version" SET DEFAULT 3;--> statement-breakpoint
ALTER TABLE "series_analysis_release_state" ALTER COLUMN "validation_contract_id" SET DEFAULT 'series-analysis-artifact-v3-full-validation-v1';--> statement-breakpoint
ALTER TABLE "series_analysis_artifacts" ADD CONSTRAINT "series_analysis_artifacts_validation_schema_check" CHECK (("series_analysis_artifacts"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v2-full-validation-v1' OR "series_analysis_artifacts"."artifact_schema_version" = 2)
      AND ("series_analysis_artifacts"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v3-full-validation-v1' OR "series_analysis_artifacts"."artifact_schema_version" = 3));--> statement-breakpoint
ALTER TABLE "series_analysis_campaign_targets" ADD CONSTRAINT "series_analysis_campaign_targets_validation_schema_check" CHECK (("series_analysis_campaign_targets"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v2-full-validation-v1' OR "series_analysis_campaign_targets"."artifact_schema_version" = 2)
      AND ("series_analysis_campaign_targets"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v3-full-validation-v1' OR "series_analysis_campaign_targets"."artifact_schema_version" = 3));--> statement-breakpoint
ALTER TABLE "series_analysis_campaigns" ADD CONSTRAINT "series_analysis_campaigns_validation_schema_check" CHECK (("series_analysis_campaigns"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v2-full-validation-v1' OR "series_analysis_campaigns"."artifact_schema_version" = 2)
      AND ("series_analysis_campaigns"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v3-full-validation-v1' OR "series_analysis_campaigns"."artifact_schema_version" = 3));--> statement-breakpoint
ALTER TABLE "series_analysis_job_attempts" ADD CONSTRAINT "series_analysis_job_attempts_validation_schema_check" CHECK (("series_analysis_job_attempts"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v2-full-validation-v1' OR "series_analysis_job_attempts"."artifact_schema_version" = 2)
      AND ("series_analysis_job_attempts"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v3-full-validation-v1' OR "series_analysis_job_attempts"."artifact_schema_version" = 3));--> statement-breakpoint
ALTER TABLE "series_analysis_job_requests" ADD CONSTRAINT "series_analysis_job_requests_validation_schema_check" CHECK (("series_analysis_job_requests"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v2-full-validation-v1' OR "series_analysis_job_requests"."artifact_schema_version" = 2)
      AND ("series_analysis_job_requests"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v3-full-validation-v1' OR "series_analysis_job_requests"."artifact_schema_version" = 3));--> statement-breakpoint
ALTER TABLE "series_analysis_jobs" ADD CONSTRAINT "series_analysis_jobs_validation_schema_check" CHECK (("series_analysis_jobs"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v2-full-validation-v1' OR "series_analysis_jobs"."artifact_schema_version" = 2)
      AND ("series_analysis_jobs"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v3-full-validation-v1' OR "series_analysis_jobs"."artifact_schema_version" = 3));--> statement-breakpoint
ALTER TABLE "series_analysis_release_state" ADD CONSTRAINT "series_analysis_release_state_validation_schema_check" CHECK (("series_analysis_release_state"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v2-full-validation-v1' OR "series_analysis_release_state"."artifact_schema_version" = 2)
      AND ("series_analysis_release_state"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v3-full-validation-v1' OR "series_analysis_release_state"."artifact_schema_version" = 3));--> statement-breakpoint
ALTER TABLE "series_analysis_title_states" ADD CONSTRAINT "series_analysis_title_states_validation_schema_check" CHECK (("series_analysis_title_states"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v2-full-validation-v1' OR "series_analysis_title_states"."artifact_schema_version" = 2)
      AND ("series_analysis_title_states"."validation_contract_id" IS DISTINCT FROM 'series-analysis-artifact-v3-full-validation-v1' OR "series_analysis_title_states"."artifact_schema_version" = 3));